Fangorn/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tower.Models.ClientViewModels;
using Microsoft.AspNetCore.Identity;
using Tower.Data;
using Tower.Models;
using Tower.Models.ClientViewModels;
using Microsoft.EntityFrameworkCore;
using Tower.Models.LocationViewModels;

namespace Tower.Controllers
{
    public class ClientController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public ClientController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new ListClients();

            model.Clients = _context.Client.Include(c => c.Address).ToList();

            return View("ClientListView", model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new CreateClient
            {

            };
            return View("CreateClient", model);

        }

        [HttpPost]
        public async Task<IActionResult> PostCreateClient(CreateClient ClientViewData)
        {
            if (ModelState.IsValid)
            {
                Address address = new Address
                {
                    Street = ClientViewData.Address.Street,
                    Apartment = ClientViewData.Address.Apartment,
                    City = ClientViewData.Address.City,
                    Country = ClientViewData.Address.Country,
                    State = ClientViewData.Address.State,
                    Zip = ClientViewData.Address.Zip
                };
                _context.Add(address);

                Client client = new Client
                {
                    Name = ClientViewData.Name,
                    Email = ClientViewData.Email,
                    Phone = ClientViewData.Phone,
                    Address = address
                };
                _context.Add(address);
                _context.Add(client);
                await _context.SaveChangesAsync();


            }


            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var clientModel = await _context.Client
                 .Include(c => c.Address)
                 .SingleOrDefaultAsync(c => c.Id == Id);
            EditClient client = new EditClient
            {
                Id = clientModel.Id,
                Name = clientModel.Name,
                EmailAddress = clientModel.Email,
                Phone = clientModel.Phone,
                Address = clientModel.Address,
                MainContact = clientModel.MainContact
            };

            return View("ClientEditView", client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int Id, EditClient editModel)
        {
            //find client
            var client = _context.Client
                .Include(a=>a.Address)
                .SingleOrDefault(c => c.Id == Id);
            
            if (client == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                client.Id = editModel.Id;
                client.Email = editModel.EmailAddress;
                client.Name = editModel.Name;
                client.Phone = editModel.Phone;
                client.MainContact = editModel.MainContact;
                client.Address.Street = editModel.Address.Street; 
                client.Address.Apartment = editModel.Address.Apartment;
                client.Address.City = editModel.Address.City;
                client.Address.State = editModel.Address.State;
                client.Address.Zip = editModel.Address.Zip;

                _context.Update(client);

                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int Id)
        {
            var client = _context.Client
                .Include(c=>c.Address).
                SingleOrDefault(c => c.Id == Id);

            if (client == null)
            {
                return NotFound();
            }

            DetailsClient model = new DetailsClient
            {
                Id = client.Id,
                Name = client.Name,
                EmailAddress = client.Email,
                Address = client.Address,
                MainContact = client.MainContact,
                Phone = client.Phone
            };

            return View("ClientDetailView", model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var client = _context.Client.SingleOrDefault(c => c.Id == Id);

            if (client == null)
            {
                return NotFound();
            }

            return View("ClientDeleteView", client);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int Id)
        {
            var client = _context.Client.SingleOrDefault(c => c.Id == Id);

            if (client == null)
            {
                return NotFound();
            }


            _context.Remove(client);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        #region Search
        [HttpPost]
        public async Task<IActionResult> IndexSearch(string search)
        {
            if (!String.IsNullOrEmpty(search))
            {
                var Clients = await _context.Clients
                    .Where(t => t.Name.Contains(search) || t.Email.Contains(search))
                    .ToListAsync();
                var model = new ListClients();
                model.Clients = Clients;
                return View("ClientListView", model);
            }

            return RedirectToAction("Index");

        }
        #endregion Search

        [ActionName("Clients")]
        public IActionResult getClients()
        {

            return RedirectToAction("Index");
        }

    }
}

Fangorn/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tower.Models.ClientViewModels;
using Microsoft.AspNetCore.Identity;
using Tower.Data;
using Tower.Models;

using Microsoft.EntityFrameworkCore;
using Tower.Models.LocationViewModels;
using Tower.Models.SettingsViewModels;

namespace Tower.Controllers
{
    public class SettingsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public SettingsController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //get settings from DB. If none exist, create one.

            var settings = _context.SiteSettings.FirstOrDefault();

            if (settings == null)
            {
                Settings model = new Settings();

                model.ChargeRate = 0;
                model.SiteName = "Tower";

                _context.Add(model);
                _context.SaveChanges();

                return View(model);
            }

            
            
            return View(settings);
            
            
        }

        [HttpGet]
        public IActionResult Edit()
        {
            var settings = _context.SiteSettings.FirstOrDefault();

            if (settings == null)
            {
                Settings model = new Settings();

                model.ChargeRate = 0;
                model.SiteName = "Tower";

                _context.Add(model);
                _context.SaveChanges();

                return View(model);
            }
            
            return View(settings);
        }


        [HttpPost]
        public async Task<IActionResult> EditPost(Settings model)
        {
            var settings = _context.SiteSettings.FirstOrDefault();

            if (ModelState.IsValid)
            {
                settings.SiteName = model.SiteName;
                settings.ChargeRate = model.ChargeRate;

                _context.Update(settings);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

    }
}

Fangorn/Controllers/TeamsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tower.Data;
using Tower.Models.TeamViewModels;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Tower.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TeamsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            return View(await _context.Teams.ToListAsync());
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //ThenInclude will grab additional attributes from related tables.
            var team = await _context.Teams
                .Include(t => t.Members).ThenInclude(m => m.User)
                .SingleOrDefaultAsync(m => m.Id == id);
                
            
            
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Teams/Create
        //ModelView
        public IActionResult CreateTeam()
        {
            
            var users = _context.Users.ToList();
            CreateTeamViewModel model = new CreateTeamViewModel
            {
                Users = new MultiSelectList(users)
            };

            return View(model);
        }

        // POST: Teams/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTeam([Bind("Name,Description")] CreateTeamViewModel createTeam, string[] members)
        {
            if (ModelState.IsValid)
            {
                //Many-to-Many relationship
                Team team = new Team
                {
                    Members = new List<TeamUser>(),
                    Description = createTeam.Description,
                    Name = createTeam.Name
                };
                _context.Add(team);

                //recent
                await _context.SaveChangesAsync();

                foreach (var member in members )
                {

                    var savedTeam = (from t in _context.Teams where t.Name == team.Name select team).SingleOrDefault();
                    //fails if not found.
                    var user = (from u in _context.Users where u.Email == member select u).SingleOrDefault();
                    var TeamUser = new TeamUser { TeamId = savedTeam.Id, Team = savedTeam, UserId = user.Id, User = user };
                    team.Members.Append(TeamUser);
                    _context.Add(TeamUser);
                }

                
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
                
            }
            return View();
        }

        
        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.SingleOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Team team)
        {
            if (id != team.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .SingleOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Teams.SingleOrDefaultAsync(m => m.Id == id);
            _context.Teams.Remove(team);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool TeamExists(int id)
        {
            return _context.Teams.Any(e => e.Id == id);
        }*/
    }
}

Fangorn/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tower</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/simple-sidebar.css" rel="stylesheet">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        
        <link href="~/css/simple-sidebar.css" rel="stylesheet"/>
    </environment>
 
    
</head>

<body class="body-site">
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Tower</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a></li>
                    <li><a asp-area="" asp-controller="ServiceOrder" asp-action="Index">Service Orders</a></li>
                    <li><a asp-area="" asp-controller="Tracker" asp-action="Index">Track Time</a></li>
                    <li><a asp-area="" asp-controller="Project" asp-action="Index">Projects</a></li>
                    <li><a asp-area="" asp-controller="Client" asp-action="Index">Clients</a></li>
                    <li><a asp-area="" asp-controller="Teams" asp-action="Index">Teams</a>
                    <li><a asp-area="" asp-controller="Settings" asp-action="Index">Settings</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")

            </div>
        </div>
    </nav>


    <div class="container-fluid">

        <div class="row">
            <nav id="sidebar" class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
                
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a></li>
                        @{ Tower.Views.MenuFactory factory = new Tower.Views.MenuFactory(); try
            {
                var controllerName = ViewContext.RouteData.Values["controller"].ToString(); Tower.Views.IMenu menu = factory.getMenu(controllerName); foreach (String menuItem in menu.getActions())
                {
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller=@menu.getController() asp-action=@menuItem>@menuItem</a></li>
                                }

                            }

                            catch
                            {

                                Tower.Views.IMenu menu = factory.getMenu("Default");

                                foreach (String menuItem in menu.getActions())
                                {
                                    <a asp-area="" asp-controller=@menu.getController() asp-action=@menuItem>@menuItem</a>
                                }

                            }



                        }

                    </ul>
            </nav>
            </div>





            <div class="container body-content">
                
                <div class="jumbotron">
                    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Actions</span>
                    @RenderBody()
                </div>

                <hr />
                <footer class="footer">
                    <ul class="list-inline">
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    </ul>
                    <p>&copy; In Development - 2017 - Tower</p>
                </footer>
            </div>

        </div>


    

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">

        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>


    </environment>
    

    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)

    <script>
        function openNav() {

            document.getElementById("sidebar").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("sidebar").style.width = "0";
        }
    
    </script>



</body>











</html>

Fangorn/Views/Shared/_dashboard.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@section Styles {
    link href="~/css/sidebar.css" rel="stylesheet" type="text/css" />
}


@if (SignInManager.IsSignedIn(User))
{




}

else
{

}




Fangorn/Views/Shared/_dashboardOld.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<head>
    <link href="~/css/sidebar.css" rel="stylesheet" type="text/css" />

</head>



@if (SignInManager.IsSignedIn(User))
{

    <div class="col-xs-2 col-sm-2 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="sidebar-nav">
                <ul class="nav">
                    <li class="active"><a href="#">Tower</a></li>
                    <li><a href="#">My Profile</a></li>
                    <li><a href="#">My Teams</a></li>
                    <li class="nav-divider"></li>
                    <li><a href="#">Link</a></li>
                    <li><a href="#">Link</a></li>
                    <li><a href="#">Link</a></li>
                    <li class="nav-divider"></li>
                    <li><a href="#">Link</a></li>
                    <li><a href="#">Link</a></li>
                </ul>
            
        </div>

    </div>

}

else
{

}
